apiVersion: apps/v1
kind: Deployment
metadata: 
     name: golang
     labels: 
         myname: xyz
spec: 
   replicas: 1
   selector: 
     matchLabels: 
          myname: xyz
   template: 
        metadata: 
          labels: 
            myname: xyz
        spec: 
          containers: 
            - name: mygolang
              image: rtxverma123/golang
              ports: 
                 - containerPort: 5000
